# Generated by Django 3.2.19 on 2023-11-24 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branches',
            name='branchStatus',
            field=models.BooleanField(default=True),
        ),
    ]
