# Generated by Django 3.2.19 on 2023-11-27 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquirydetails', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquirymodel',
            name='yearOfPassing',
            field=models.PositiveBigIntegerField(),
        ),
    ]
