# Generated by Django 3.2.19 on 2023-11-27 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquirydetails', '0002_alter_enquirymodel_yearofpassing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquirymodel',
            name='contact',
            field=models.PositiveBigIntegerField(),
        ),
        migrations.AlterField(
            model_name='enquirymodel',
            name='yearOfPassing',
            field=models.IntegerField(),
        ),
    ]
