# Generated by Django 3.2.19 on 2023-11-23 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Batches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batchType', models.CharField(max_length=100)),
                ('startDate', models.DateField()),
                ('batchTime', models.CharField(max_length=50)),
                ('seatAvailable', models.BooleanField(default=True)),
                ('duration', models.CharField(max_length=50)),
                ('batchStatus', models.CharField(max_length=50)),
                ('courseId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.courses')),
            ],
        ),
    ]
